version: '3.7'
services:
    mysql:
        image: mysql:5.7
        container_name: docker-mysql
        ports:
            - "3306:3306"
        restart: always
        volumes:
            - ./data:/var/lib/mysql
            - ./config:/etc/mysql
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: "your_password"
            MYSQL_DATABASE: "my_database"
        env_file:
            - .env
        networks:
            - local_network
    adminer:
        image: adminer
        ports:
        - 8080:8080
        networks:
        - local_network

networks:
    local_network:
        driver: bridge
